name: Kotlin application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Adjust the version as needed

    - name: Build and Test
      run: |
        ./gradlew build
        ./gradlew test

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/*.jar